### ISSUE TITLE
Arnav

### ISSUE THREAD

**Issue by arnavgrg** [sjoshi804/virtual-career-fair#110]
- [x] Update User Login Page
- [x] Complete Recruiter Login Page
- [x] Complete Organizer Login Page
- [x] Complete Backend Class Diagram
- [x] Look through entire flow and plan out what's on the 5 minute video4
- [x] Start working on integrating other endpoints

**Comment by sjoshi804** [comment]
- [ ] Recruiter Redirect
- [ ] Dynamic population of student profile
- [ ] Dynamic population of recruiter profile
- [ ] Dynamic population of organizer profile

**Comment by sjoshi804** [comment]
- [ ] Keep track of good data to put in atlas
